# Generated by Django 4.2.4 on 2023-09-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_match_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='response',
            field=models.JSONField(default=list, null=True),
        ),
    ]
